// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PadelApp.Datos;

#nullable disable

namespace PadelApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PadelApp.Modelos.Anuncio", b =>
                {
                    b.Property<int>("idAnuncio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idAnuncio"));

                    b.Property<string>("descripcion")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("fechaEvento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fechaExpiracion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("fecha_actualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<decimal?>("nivelRequerido")
                        .HasColumnType("decimal(2, 1)");

                    b.Property<bool>("permiteLlamada")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("permiteWhatsapp")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("precio")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("telefonoContacto")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<int>("tipoAnuncio")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("idAnuncio");

                    b.HasIndex("idUsuario");

                    b.ToTable("Anuncios");
                });

            modelBuilder.Entity("PadelApp.Modelos.Club", b =>
                {
                    b.Property<int>("idClub")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idClub"));

                    b.Property<bool>("activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("cif")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("fecha_actualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("nombreClub")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idClub");

                    b.ToTable("Clubes");
                });

            modelBuilder.Entity("PadelApp.Modelos.InvitacionClub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdClub")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioCreador")
                        .HasColumnType("int");

                    b.Property<bool>("Usado")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("InvitacionClubes");
                });

            modelBuilder.Entity("PadelApp.Modelos.Pista", b =>
                {
                    b.Property<int>("idPista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idPista"));

                    b.Property<bool>("activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("comentarios")
                        .HasColumnType("longtext");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fecha_actualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("idSede")
                        .HasColumnType("int");

                    b.Property<string>("nombrePista")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idPista");

                    b.HasIndex("idSede");

                    b.ToTable("Pistas");
                });

            modelBuilder.Entity("PadelApp.Modelos.RecuperacionPassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Usado")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("RecuperacionPasswords");
                });

            modelBuilder.Entity("PadelApp.Modelos.Reserva", b =>
                {
                    b.Property<int>("idReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idReserva"));

                    b.Property<string>("comentarios")
                        .HasColumnType("longtext");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("fecha_actualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("fecha_reserva")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("hora_fin")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly>("hora_inicio")
                        .HasColumnType("time(6)");

                    b.Property<int>("idPista")
                        .HasColumnType("int");

                    b.Property<int>("idUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("idReserva");

                    b.HasIndex("idPista");

                    b.HasIndex("idUsuario");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("PadelApp.Modelos.Rol", b =>
                {
                    b.Property<int>("idRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idRol"));

                    b.Property<bool>("activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("fecha_actualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("nombreRol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("idRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PadelApp.Modelos.Sede", b =>
                {
                    b.Property<int>("idSede")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idSede"));

                    b.Property<bool>("activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("direccion")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("fecha_actualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("idClub")
                        .HasColumnType("int");

                    b.Property<string>("nombreSede")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("telefono")
                        .HasColumnType("longtext");

                    b.HasKey("idSede");

                    b.HasIndex("idClub");

                    b.ToTable("Sedes");
                });

            modelBuilder.Entity("PadelApp.Modelos.Usuario", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idUsuario"));

                    b.Property<bool>("activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("apellidos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("dni_nie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("fecha_actualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("fecha_nacimiento")
                        .HasColumnType("date");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("idClub")
                        .HasColumnType("int");

                    b.Property<int>("idRol")
                        .HasColumnType("int");

                    b.Property<int>("nivel")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("telefono")
                        .HasColumnType("longtext");

                    b.HasKey("idUsuario");

                    b.HasIndex("idClub");

                    b.HasIndex("idRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PadelApp.Modelos.Anuncio", b =>
                {
                    b.HasOne("PadelApp.Modelos.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("PadelApp.Modelos.Pista", b =>
                {
                    b.HasOne("PadelApp.Modelos.Sede", "Sede")
                        .WithMany()
                        .HasForeignKey("idSede")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("PadelApp.Modelos.Reserva", b =>
                {
                    b.HasOne("PadelApp.Modelos.Pista", "Pista")
                        .WithMany()
                        .HasForeignKey("idPista")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PadelApp.Modelos.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("idUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pista");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PadelApp.Modelos.Sede", b =>
                {
                    b.HasOne("PadelApp.Modelos.Club", "Club")
                        .WithMany()
                        .HasForeignKey("idClub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("PadelApp.Modelos.Usuario", b =>
                {
                    b.HasOne("PadelApp.Modelos.Club", "Club")
                        .WithMany()
                        .HasForeignKey("idClub")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PadelApp.Modelos.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("idRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
